version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:180294222815:task-definition/LampStack-app:4"
        LoadBalancerInfo:
          ContainerName: "LampstackApplication"
          ContainerPort: 8080
        PlatformVersion: "LATEST"

